//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 09:52:03 PM EST 
//


package edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productActionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="include_network_package" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="download" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="install" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="disable_enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productActionType", propOrder = {
    "id",
    "includeNetworkPackage",
    "download",
    "install",
    "disableEnable"
})
public class ProductActionType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "include_network_package", defaultValue = "false")
    protected boolean includeNetworkPackage;
    @XmlElement(defaultValue = "false")
    protected boolean download;
    @XmlElement(defaultValue = "false")
    protected boolean install;
    @XmlElement(name = "disable_enable", defaultValue = "false")
    protected boolean disableEnable;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the includeNetworkPackage property.
     * 
     */
    public boolean isIncludeNetworkPackage() {
        return includeNetworkPackage;
    }

    /**
     * Sets the value of the includeNetworkPackage property.
     * 
     */
    public void setIncludeNetworkPackage(boolean value) {
        this.includeNetworkPackage = value;
    }

    /**
     * Gets the value of the download property.
     * 
     */
    public boolean isDownload() {
        return download;
    }

    /**
     * Sets the value of the download property.
     * 
     */
    public void setDownload(boolean value) {
        this.download = value;
    }

    /**
     * Gets the value of the install property.
     * 
     */
    public boolean isInstall() {
        return install;
    }

    /**
     * Sets the value of the install property.
     * 
     */
    public void setInstall(boolean value) {
        this.install = value;
    }

    /**
     * Gets the value of the disableEnable property.
     * 
     */
    public boolean isDisableEnable() {
        return disableEnable;
    }

    /**
     * Sets the value of the disableEnable property.
     * 
     */
    public void setDisableEnable(boolean value) {
        this.disableEnable = value;
    }

}
